global:
  resolve_timeout: 5m
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

route:
  receiver: pagerduty
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  routes:
    - match:
        severity: 'warning'
      receiver: pagerduty
    - match:
        severity: 'critical'
      receiver: pagerduty

receivers:
  - name: pagerduty
    pagerduty_configs:
      - routing_key: fc46b46b77c64e02c1fbab156915d69f
        severity: '{{ .CommonLabels.severity }}'
        send_resolved: true
